nomad/action.py
nomad/util.py

When a project is initially started and needs a static IP, no problem.
But if we stop the project, start *another* project that akso needs a
static IP, and then try to start our first project again, we'll get an
IP conflict.
This commit solves this problem by:
1. Marking containers needing a static IP in the config.
2. Re-assigning a new static IP before starting any such marked
container.

Automatically resolve static IP conflicts

---

nomad/config.py
nomad/util.py

Having the container name exactly as the project name in the
`.nomad.yml` file is kind of limiting because you can't have the project
live in multiple containers (to try an experimental feature, for
example).
With this commit, we set a `user.nomad.homedir` config at container
creation to the absolute path of our project (config file). When we try
to run `nomad up` from a directory that isn't referenced by any
container, we create a new one and mangle its name if there's a naming
conflict.

Allow the same project to live in separate containers

---

README.md
nomad/container.py

Add support for pull mode: this allows to create containers without having to copy them. The image are fetched from the linuxcontainers image server by default (but this can be configured of course).
One thing: for now the "local" mode remains the default mode for LXD-Nomad, but I think that the "pull" mode should be the default mode because it allows a workflow that is much more simple than the "local" mode (you don't have to initially copy the image and its aliases before using the nomad command).

Add pull mode

---

docs/getting_started.rst

The manual installation of pip3 should be a last resort. It's not a good
idea to do this on a Debian/Ubuntu system, so we should not suggest it.
Also, stackoferflow has a better overall answer for edge cases.

docs: improve pip3 installation notes

---

lxdock/container.py
lxdock/guests/__init__.py
lxdock/guests/alpine.py
lxdock/guests/base.py
lxdock/guests/centos.py
lxdock/guests/fedora.py
lxdock/guests/gentoo.py
lxdock/guests/opensuse.py
lxdock/guests/oracle.py
tests/integration/test_container.py
tests/integration/test_project.py
tests/unit/guests/test_alpine.py
tests/unit/guests/test_centos.py
tests/unit/guests/test_fedora.py
tests/unit/guests/test_gentoo.py
tests/unit/guests/test_opensuse.py
tests/unit/guests/test_oracle.py

1. Also fixed the regex for detecting Linux distro.
2. Replaced `bash` as `su -m root` in `lxdock shell`, to use the default shell of the Linux distro.

New: Add guests - Alpine, Centos, Fedora, Gentoo, OpenSUSE, Oracle. Closes #29.

---

lxdock/cli/main.py
tests/unit/cli/test_main.py

Remove `parse_args()` mocking from CLI tests and replace it with the
ability, in `LXDock()`, to override parsed args with arbitrary args.
This makes tests much less heavy and a little less tautological. It also
uncovered cases where mocked parsed args were actually wrong, making us
test the wrong `call_args`.

De-mock CLI tests

---

docs/conf.rst
docs/getting_started.rst

The old readme had something about trying privileged mode when
encountering problems and this disappeared in the new docs. Considering
that `debian/jessie` is a popular image and that it doesn't work in
unprivileged mode, I think it's important to have that section to avoid
being swamped with troubleshooting issues of this type on github.

docs: add "Problems?" section to "Getting Started"

---

contrib/completion/zsh/_lxdock
docs/getting_started.rst

Ref issue #25.
Commands for completion (according to lxdock help messages, and `-h` options are not included):
- lxdock config [-h] [--containers]
- lxdock destroy [-h] [-f] [name [name ...]]
- lxdock halt [-h] [name [name ...]]
- lxdock help [-h] [subcommand]
- lxdock init [-h] [-f] [--image IMAGE] [--project PROJECT]
- lxdock provision [-h] [name [name ...]]
- lxdock shell [-h] [-u USERNAME] [name]
- lxdock status [-h] [name [name ...]]
- lxdock up [-h] [name [name ...]]
How to test:
1. Install zsh and follow the updated doc to configure the completion.
2. Restart zsh.
3. Create a test folder and an example `lxdock.yml` in it, or go to an existing folder that contains file `lxdock.yml`. (It could also be: .lxdock.yml, .lxdock.yaml, lxdock.yml, lxdock.yaml, .nomad.yml, .nomad.yaml, …

New: zsh completion. Closes #25.

---

setup.py

As we can see in #49 and #50, our integration tests broke due to a
recent ws4py release. Until we figure out how to fix the problem
upstream, we pin this dependency to make our tests run again.

Temporarily pin ws4py sub-dependency to v0.3.4

---

lxdock/container.py
lxdock/guests/alpine.py
lxdock/guests/archlinux.py
lxdock/guests/base.py
lxdock/guests/centos.py
lxdock/guests/debian.py
lxdock/guests/fedora.py
lxdock/guests/gentoo.py
lxdock/guests/opensuse.py
lxdock/guests/oracle.py
tests/unit/guests/test_alpine.py
tests/unit/guests/test_archlinux.py
tests/unit/guests/test_centos.py
tests/unit/guests/test_debian.py
tests/unit/guests/test_fedora.py
tests/unit/guests/test_gentoo.py
tests/unit/guests/test_opensuse.py
tests/unit/guests/test_oracle.py

Those packages were always a misnomer. They're not really "barebone",
they're required only for ansible to be able to run properly. With new
provisioners coming in soon, it becomes inefficient to install those
packages on *every* container, even those not running ansible.
Moreover, it has an immediate side effect: it makes some integration
tests run much faster.

Make "barebone" packages be installed for ansible only

---

docs/conf.rst
lxdock/conf/schema.py
lxdock/container.py
lxdock/guests/base.py
tests/integration/test_container.py
tests/unit/guests/test_base.py

Adds support for user passwords, passwords must be encrypted using crypt, for example:
mkpasswd --method=sha-512 'password'
Includes tests and documentation update.

Add support for custom user passwords

---

docs/conf.rst
lxdock/conf/schema.py
lxdock/container.py
tests/integration/test_container.py

Add a new config dictionary in the `shell` key: `environment`. All
values in this dictionary are passed to LXD's config under the
"environment.*" config type.
We set this config when `shell` is called, which is a bit at odds with
the rest of the container config, which is usually set at creation time.
We do this so that a user who fiddles with her `lxdock.yml` file doesn't
have to restart/recreate her container to benefit from the change she's
just made. They will be effective on the next `lxdock shell` call.

shell: add a way to set environment variables

---

docs/conf.rst
lxdock/conf/config.py
lxdock/conf/schema.py
lxdock/container.py
tests/integration/test_container.py
tests/unit/conf/fixtures/lxc_config/lxdock.yml
tests/unit/conf/test_config.py

Provide a way to pass custom LXC parameters for a container, as an advanced setting.
The need for this arose from this bug:
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1575779
The only way I have to found to work around is to set the container to `raw.lxc: lxc.aa_profile=unconfined`.

Accept custom LXC configuration

---

docs/conf.rst
lxdock/conf/interpolation.py
tests/unit/conf/fixtures/project_with_dynamic_variables/lxdock.yml
tests/unit/conf/fixtures/project_with_dynamic_variables_and_env_file/.env
tests/unit/conf/fixtures/project_with_dynamic_variables_and_env_file/lxdock.yml
tests/unit/conf/test_config.py

Only allow ${var} style variables but not $var anymore.
The latter causes issues with hashed password which then need to be escaped and that gets messy.
That also means that escaping of the $ character is no longer needed.

Use stricter variable substitution

---

docs/conf.rst
docs/release_notes/v0.3.rst
lxdock/conf/schema.py
lxdock/container.py
tests/integration/test_container.py

This pull request allows to set `profiles` in LXDock files, to use existing system-wide profiles.
In the future, LXDock may want to consider project-wise definition, etc.

New: basic support for LXC profiles. Refs #68

---

docs/conf.rst
docs/usage/shared_folders.rst
lxdock/conf/schema.py
lxdock/container.py

This option defaults to True if not set so the existing behaviour stays the same.
Note: this replaces older PR #74 which can now be closed.
Not sure if a test is needed for this, as it changes very little

Add option to disable setting host ACL on a share

---

docs/cli/up.rst
lxdock/cli/main.py
lxdock/constants.py
lxdock/container.py
lxdock/project.py
tests/unit/cli/test_main.py

This PR adds support for using the `up` command as follows:
$ lxdock up --provision
$ lxdock up --no-provision

Added support for provisioning-specific arguments to the up command

---

docs/getting_started.rst

Since a while I'm maintaining a community build of the `lxd` package for Fedora on COPR ([ganto/lxd](https://copr.fedorainfracloud.org/coprs/ganto/lxd/)). Recently I found `lxdock` and since I was a frequent Vagrant/LXC user, I found some interest in LXDock too. Therefore I also started a COPR repository [ganto/lxdock](https://copr.fedorainfracloud.org/coprs/ganto/lxdock/).
Those repositories are maintained on a best effort basis. Feedback is always welcome. 
Are you interested in adding a hint to this to your documentation?

Add documentation of experimental LXD(ock) setup on Fedora

---

.codecov.yml

These spurious failures caused by codecov are mightily annoying, even
with comments off. Red X in github are supposed to mean "DO NOT MERGE".
But the thing is, codecov checks are so tight that they trigger alarms
for perfectly good PR, which end up making us *ignore* those big red X
and thus beat the whole purpose behind them.

Make codecov relax

---

.travis.yml
docs/provisioners/ansible.rst
lxdock/provisioners/ansible.py
lxdock/test/fakes.py
requirements-dev.txt
requirements-tests.txt
tests/integration/test_container.py
tests/unit/provisioners/test_ansible.py
tox.ini

The "lxd" transport in ansible allows us to provision our containers
without SSH, directly through "lxc exec" calls!
I had the idea for quite a while that I should explore the possibility
of plugging "lxc exec" into ansible, but I didn't know that the plug was
already there, ready to be used! Had I known that, I would have used it
from the start, it would have saved me SSH fiddling...
Also, you know that small "HOME=" line in tox.ini? I've spent **hours**
debugging this. My tests would fail **only** when running into tox, not
when running directly through pytest. That was very puzzling. Live and
learn...

Make ansible use the "lxd" transport instead of ssh

---

lxdock/test/fixtures.py
tests/integration/fixtures/project01/lxdock.yml
tests/integration/fixtures/project02/lxdock.yml
tests/integration/fixtures/project03/lxdock.yml
tests/integration/test_container.py
tests/integration/test_project.py

Alpine images are 2MB and xenial ones are 90MB!
On my machine, it makes the full test suite go from 356s to 182s, which
I think makes it very worthwhile!

Replace ubuntu/xenial with alpine/3.6 in integration tests

---

docs/release_notes/v0.4.rst
lxdock/__init__.py

lxdock hasn't seen activity in a while and I'd like to use my lxd_transport option in my system-installed lxdock.
Besides, the recently-removed `requests<=2.16` hack in `setup.py` made my system lxdock complain when my system version of requests bumped up. I'd like to fix that.

Release v0.4.0

---

lxdock/container.py
tests/integration/test_container.py

When running `lxdock halt` after having only a subset if our containers
being created, we would end up in this annoying situation where missing
containers would be created and then halted. Not anymore.

Don't create containers on "halt" command

---

lxdock/conf/config.py

Moving `config.interpolate()` before `schema` check to support interpolated variables in configuration file to address issue #107 
All tests pass.

Fix issue with environmental variables.

---

.travis.yml
Makefile
requirements-dev.txt
tests/integration/test_project.py

This commit is a squashed version of last 40 commits in PR #119
* Use snap version of lxd and continue to use Trusty for now as it seems more reliable
* Fix import ordering in test_project.py that seems to have come from an updated version of isort
* Move Travis setup to Makefile where lxd is installed from snap and a network setup
* Needed to use sudo -E workaround to apply lxd group to travis user before running tests
* Pin version of Sphinx used because latest version was going into a recursion loop during pip install

Tests are working again on Travis using snap

---

lxdock/conf/schema.py
lxdock/container.py
lxdock/guests/base.py
tests/unit/guests/test_base.py

Some images like debian will just create new users with /bin/sh. Doing it via useradd is a lot less work than using something like ansible to provision the user with a particular shell.

Create user with a custom shell

---

lxdock/conf/schema.py
lxdock/container.py

Some containers may be slow to boot up. The default 10 second wait might not be enough.

Allow wait timeout to be changed for IP

---

.travis.yml

Don't create symlink in /usr/bin
I don't think this is needed anymore, it should all be handled in ci-base-setup.sh

Tidyup .travis.yml

---

lxdock/conf/schema.py
lxdock/container.py
lxdock/guests/base.py
lxdock/guests/gentoo.py
lxdock/hosts/base.py
tests/integration/test_container.py
tests/integration/test_project.py
tests/unit/guests/test_base.py
tests/unit/hosts/test_base.py

Fixes #114 (lxdock shell doesn't set the correct env vars, commit 1) and #116 (shared folder issues, commit 2).
Fix for #116 is derived from https://stgraber.org/2017/06/15/custom-user-mappings-in-lxd-containers/.
This is kind of a WIP as there's no tests. Some finer points needs to be debated as well. A todo list is as follows:
About setting up your system for this, you need to run:
```
printf "lxd:$(id -u):1\nroot:$(id -u):1\n" | sudo tee -a /etc/subuid
printf "lxd:$(id -g):1\nroot:$(id -g):1\n" | sudo tee -a /etc/subgid
sudo systemctl restart lxd
```
Demonstration of how this works:
```
[thinkpadw530:~/projects/test-lxdock]$ ls -l
total 16
-rw-rw-r-- 1 shuhao shuhao    7 Mar  4 00:25 abc
-rw-rw-r-- 1 shuhao shuhao    5 Mar  4 00:25 bde
drwxrwxr-x 8 shuhao shuhao 4096 Mar  3 23:03 …
```

 Use raw.idmap to map shared folders' permissions

---

scripts/ci-base-setup.sh

This allows testing of raw.idmap on vagrant box as well as Travis CI.

Setup /etc/subuid and /etc/subgid in ci base setup

---

contrib/completion/zsh/_lxdock
lxdock/cli/main.py
lxdock/container.py
tests/integration/test_container.py
tests/integration/test_project.py
tests/unit/cli/test_main.py

The shell command feature did not seem to work when running two commands because it was using shlex.quote on each argument.
See: issue #129
With the current syntax I was unable to work out how to simply run two commands in a container, Vagrant uses this much simpler syntax which makes much more sense:
vagrant ssh -c "command1; command2"
Also Vagrant will produce an error if you add another argument so this will not work:
vagrant ssh -c command1 command2
It seemed lxdock followed something like that except it auto quoted each argument, it was quite confusing and I couldn't figure out how two run two commands and that produced an error.
I have changed lxdock to be the same as how vagrant works:
lxdock shell -c "command1; command2"
Fixed tests and updated zsh config, the bash one doesn't …

Fix shell -c command is now like Vagrant

---

docs/contributing.rst
docs/getting_started.rst
docs/glossary.rst

* Mostly updating the get_started.rst page and documenting Snap installation method
* Also add recommendation about installing lxdock in a virtualenv to discourage sudo pip installs
* Add note about migrating from apt to Snap version of LXD without going into too much detail
* Add section to getting_started.rst about setting up the host for shares and remove setfacl reference
* Mention Vagrant test box in contributing.rst page
* Don't be too assertive about coverage (exclamation mark), yes we want to be strict, but sometimes a small drop is unavoidable and should be discussable on an issue
* Found one typo in glossary.rst

Updating docs for 0.5 release part 1

---

lxdock/conf/config.py
lxdock/conf/schema.py
lxdock/conf/validators.py
lxdock/container.py
tests/unit/conf/test_validators.py

Allows shares to be specified with ~ on the host.
This allows one to share things like .ssh/.gnupg and other stuff easier into the container.
Additionally, I'm adding an entry to allow the specification of additional disk options as documented by https://github.com/lxc/lxd/blob/master/doc/containers.md#type-disk
@robvdl

Expanduser for shares as well as additional share properties.

---

requirements-tests.txt

It appears that Ansible 2.5 no longer supports Python 3.4
Since Ubuntu 14.04 LTS is still supported which comes with Python 3.4, we should pin Ansible at least until April 2019 when Ubuntu 14.04 goes out of support.
After that period we could possibly remove the Python 3.4 job on Travis and start testing against 3.7 instead

Pin ansible < 2.5 to keep supporting Python 3.4

---

scripts/ci-base-setup.sh
setup.py

Tests were failing because the bridge already existed.

Fix Travis CI tests, lxd init already sets up a bridge now

---

lxdock/guests/base.py

This allows the stdout/stderr of the shell provisioner to be displayed in the terminal in real time. Fixes #104.
Using a similar technique, I can get ansible running on the container itself without having to ssh. I'll be working on this soon (tomorrow?) as I need this functionality for my setup.

See shell provisioner stdout and stderr

---

.travis.yml
lxdock/test/fixtures.py
requirements-tests.txt
setup.py
tests/integration/fixtures/project01/lxdock.yml
tests/integration/fixtures/project02/lxdock.yml
tests/integration/fixtures/project03/lxdock.yml
tests/integration/test_container.py
tests/integration/test_project.py
tests/unit/conf/test_schema.py
tests/unit/provisioners/test_ansible.py

Travis build currently fails.
The linting in the travis build failed, due to a newer flake8 version. See https://github.com/MathSci/fecon236/issues/6 for reference.
Prefixing the string holding a regex with `r` (according to the current python conventions) fixes that.
Newer versions of pycov require a newer version of pytest.
The tests used *alpine/3.6* as a test image, which does not exist anymore in the standard remote. Version bump to 3.11.
The new version of alpine requires a root password to be set manually, otherwise SSH (and thus ansible) won't work.
In the past, the pylxd version used (in the tests) was restricted to 2.2.7 (due to an upstream bug mentioned in #155), but this broke with the introduction of #163 which used newer API signatures.
The upstream bug has been fixed, so an …

Fix travis build

---

Vagrantfile
docs/contributing.rst
requirements-tests.txt
scripts/vagrant-base-setup.sh

I have updated and fixed the usage of the Vagrant box for the test environment and added documentation about its usage, too (which closes part of #122 ).

Fix and document Vagrant usage

---

setup.py

At the time PyYAML 4.x hadn't been released yet, now we're upto 5.3
Have tested and can't see any breakages other than the existing breakages which seem pylxd related.
Thank you for contributing to LXDock! A list of simple rules is available on the online
documentation to help you contribute to this project: http://lxdock.readthedocs.io/en/latest/contributing.html.
Please review these guidelines before submitting your pull request!

Upgrade PyYAML, update upper limit from pinned version

---

lxdock/container.py
lxdock/guests/base.py
lxdock/provisioners/ansible.py
tests/integration/test_container.py
tests/unit/guests/test_base.py
tests/unit/provisioners/test_ansible.py

Previously, the SSH key from the host user was only installed in the authorized_keys file of the root user in the container. It only did that, if the ansible provisioner was used.
This path changes two thing:
* The key is always installed in the container, even without ansible being used
* The key is installed for all users created by lxdock, not just root
This fixes #167

Install SSH key in authorized_keys of all users created by lxdock

---

lxdock/container.py

Should have spacing around +, pycodestyle should have picked this up, not sure why it didn't.
Thank you for contributing to LXDock! A list of simple rules is available on the online
documentation to help you contribute to this project: http://lxdock.readthedocs.io/en/latest/contributing.html.
Please review these guidelines before submitting your pull request!

Fix pycodestyle issue that was undetected + typo

---

docs/cli/index.rst
docs/cli/init.rst
docs/conf.rst
docs/contributing.rst
docs/glossary.rst
docs/provisioners/ansible.rst
docs/provisioners/index.rst
docs/usage/provisioning.rst
lxdock/cli/exceptions.py
lxdock/conf/exceptions.py
lxdock/conf/validators.py
lxdock/exceptions.py
lxdock/guests/base.py
lxdock/hosts/base.py
lxdock/network.py
lxdock/utils/identifier.py
lxdock/utils/metaclass.py
tests/unit/cli/test_main.py
tests/unit/conf/test_config.py

* Also linting of docs discovered that "_Ansible:" was there twice
Thank you for contributing to LXDock! A list of simple rules is available on the online
documentation to help you contribute to this project: http://lxdock.readthedocs.io/en/latest/contributing.html.
Please review these guidelines before submitting your pull request!

Fix a whole bunch of typos in code, docs and tests

---

lxdock/container.py
tests/integration/test_container.py

Right now, since we are launching shell commands by first transferring a script and then launching the script as if it is a shell (see man su for the -s option), it sets the SHELL environment variable to the script.
Some applications relies on using the SHELL environment variable to launch subprocesses, which could result in a forkbomb. This PR fixes this behaviour by setting the SHELL to /bin/sh, which is accurate.
Based on original PR#153 by shuhaowu, checking to see if we get two failed tests agains latest master.
Thank you for contributing to LXDock! A list of simple rules is available on the online
documentation to help you contribute to this project: http://lxdock.readthedocs.io/en/latest/contributing.html.
Please review these guidelines before submitting your pull request!

Correctly set the SHELL variable
